plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'fr.clickdroit.uhc'
version = '1.0'
description = 'UHC Plugin'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

repositories {
    mavenCentral()

    maven {
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }

    maven {
        url = 'https://oss.sonatype.org/content/repositories/snapshots/'
    }

    maven {
        url = 'https://repo.aikar.co/content/groups/aikar/'
    }

    maven {
        url = 'https://repo.lunarclient.dev/'
    }
}

dependencies {
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    implementation 'commons-io:commons-io:2.15.1'

    // Versions compatibles Java 8
    implementation 'org.slf4j:slf4j-api:1.7.36'
    implementation 'ch.qos.logback:logback-classic:1.2.12'

    compileOnly 'org.spigotmc:spigot:1.8.8-R0.1-SNAPSHOT'

    // Test dependencies
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:3.12.4'
    testImplementation 'org.spigotmc:spigot:1.8.8-R0.1-SNAPSHOT'

    // Lunar Client Apollo
    compileOnly 'com.lunarclient:apollo-api:1.2.3'
    compileOnly 'net.kyori:adventure-api:4.14.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    archiveBaseName.set('UHC')
}
shadowJar {
    archiveBaseName.set('UHC')
    archiveClassifier.set('')
}