name: UHCAPI
main: fr.clickdroit.api.API
version: 1.0
author: clickdroit
description: API UHC permettant l'intégration de modes de jeu personnalisés
api-version: 1.8
load: STARTUP
loadbefore: []
softdepend: []
commands:
  enchant:
  finish:
  helpop:
  vanish:
  host:
    aliases: [ h ]
  inv:
    aliases: [ inventory ]
  revive:
  rules:
  scenario:
    aliases: [ scenarios ]
  tc:
    aliases: [ teamcoords ]
  view:
    aliases: [ invsee ]
  vote:
  preload:
  tprandom:
  alerts:
  whitelist:
    aliases: [ wl ]
  tphere:
  health:
  viewoffline:
  disperse:
  groupe:
    aliases: [ groupes ]
  near:
    aliases: [ playersnear,playernear ]
permissions:
  uhc.host:
    description: Accès aux commandes host
    default: op
  uhc.staff:
    description: Accès aux commandes staff
    default: op
  uhc.spectator:
    description: Commandes spectateur
    default: true
  uhc.player:
    description: Commandes joueur de base
    default: true